/**
 * ACCESS_TOKEN cookie name
 */
export const ACCESS_TOKEN = "__MARCH_ACCESS_TOKEN__"

/**
 * REFRESH_TOKEN cookie name
 */
export const REFRESH_TOKEN = "__MARCH_REFRESH_TOKEN__"

/**
 * INTEGRATIONS ACCESS_TOKEN cookie name
 */
export const GOOGLECALENDAR_ACCESS_TOKEN = "__CALENDAR_ACCESS_TOKEN__"
export const GOOGLECALENDAR_REFRESH_TOKEN = "__CALENDAR_REFRESH_TOKEN__"

/**
 * LINEAR ACCESS_TOKEN cookie name
 */
export const LINEAR_ACCESS_TOKEN = "__LINEAR_ACCESS_TOKEN__"
