/**
 * ACCESS_TOKEN cookie name
 */
export const ACCESS_TOKEN = "__EMPTYARRAY_ACCESS_TOKEN__"

/**
 * REFRESH_TOKEN cookie name
 */
export const REFRESH_TOKEN = "__EMPTYARRAY_REFRESH_TOKEN__"

/**
 * INTEGRATIONS ACCESS_TOKEN cookie name
 */
export const GOOGLECALENDAR_ACCESS_TOKEN = "__CALENDAR_ACCESS_TOKEN__"
export const GOOGLECALENDAR_REFRESH_TOKEN = "__CALENDAR_REFRESH_TOKEN__"
